export const LOGIN_EMAIL_CHANGED='LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED='LOGIN_PASSWORD_CHANGED';

export const LOGIN_SUBMIT='LOGIN_SUBMIT';
export const LOGIN_SUBMIT_FAILED='LOGIN_SUBMIT_FAILED';
export const LOGIN_SUBMIT_SUCCESS='LOGIN_SUBMIT_SUCCESS';