export const LOGIN_EMAIL_CHANGED='LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED='LOGIN_PASSWORD_CHANGED';

export const LOGIN_SUBMIT='LOGIN_SUBMIT';
export const LOGIN_SUBMIT_FAILED='LOGIN_SUBMIT_FAILED';
export const LOGIN_SUBMIT_SUCCESS='LOGIN_SUBMIT_SUCCESS';

export const LOGOUT='LOGOUT';
export const REFRESH_LOGIN='REFRESH_LOGIN';
export const REFRESH_LOGIN_FAILURE='REFRESH_LOGIN_FAILURE';
export const REFRESH_LOGIN_SUCCESS='REFRESH_LOGIN_SUCCESS';