export const ORDER_RESET_STATUS_MESSAGE='ORDER_RESET_STATUS_MESSAGE';
export const GET_ORDERS='GET_ORDERS';
export const GET_ORDERS_SUCCESS='GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE='GET_ORDERS_FAILURE';
export const GET_ORDER='GET_ORDER';
export const GET_ORDER_SUCCESS='GET_ORDER_SUCCESS';
export const GET_ORDER_FAILURE='GET_ORDER_FAILURE';