export const PRODUCT_IMAGE_CHANGED='PRODUCT_IMAGE_CHANGED';
export const PRODUCT_IMAGE_UPLOAD='PRODUCT_IMAGE_UPLOAD';
export const PRODUCT_IMAGE_UPLOAD_SUCCESS='PRODUCT_IMAGE_UPLOAD_SUCCESS';
export const PRODUCT_IMAGE_UPLOAD_FAILURE='PRODUCT_IMAGE_UPLOAD_FAILURE';
export const PRODUCT_IMAGE_LABEL_CHANGED='PRODUCT_IMAGE_LABEL_CHANGED';
/* ordering update for images */
export const PRODUCT_IMAGE_ORDER_UPDATE='PRODUCT_IMAGE_ORDER_UPDATE';
export const PRODUCT_IMAGE_ORDER_UPDATE_SUCCESS='PRODUCT_IMAGE_ORDER_UPDATE_SUCCESS';
export const PRODUCT_IMAGE_ORDER_UPDATE_FAILURE='PRODUCT_IMAGE_ORDER_UPDATE_FAILURE';
/* updating a single product image */
export const PRODUCT_IMAGE_EDIT_SINGLE='PRODUCT_IMAGE_EDIT_SINGLE';
export const PRODUCT_IMAGE_UPDATE_SINGLE='PRODUCT_IMAGE_UPDATE_SINGLE';
export const PRODUCT_IMAGE_UPDATE_SINGLE_SUCCESS='PRODUCT_IMAGE_UPDATE_SINGLE_SUCCESS';
export const PRODUCT_IMAGE_UPDATE_SINGLE_FAILURE='PRODUCT_IMAGE_UPDATE_SINGLE_FAILURE';

export const PRODUCT_IMAGE_IMAGES_CHANGED='PRODUCT_IMAGE_IMAGES_CHANGED';
export const PRODUCT_IMAGE_RESET_STATUS_MESSAGE='PRODUCT_IMAGE_RESET_STATUS_MESSAGE';