export const PRODUCT_IMAGE_CHANGED='PRODUCT_IMAGE_CHANGED';
export const PRODUCT_IMAGE_UPLOAD='PRODUCT_IMAGE_UPLOAD';
export const PRODUCT_IMAGE_UPLOAD_SUCCESS='PRODUCT_IMAGE_UPLOAD_SUCCESS';
export const PRODUCT_IMAGE_UPLOAD_FAILURE='PRODUCT_IMAGE_UPLOAD_FAILURE';